# Page settings

baseurl = "http://www.annasimbirtsev.me/"
languageCode = "en-us"
title = "Anna Simbirtsev Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Anna Simbirtsev"
        tagline = "Senior Full Stack Developer"
        avatar = "portrait.jpg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: asimbirtsev@email.com"
        title = "asimbirtsev@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+14167297331"
        title = "+14167297331"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/anna-simbirtsev"
        title = "linkedin.com/in/anna-simbirtsev"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Honours Bachelor in Computer Science"
        college = "University of Toronto"
        dates = "1998 - 2002"

        [[params.education.list]]
        degree = "Minor in Mathematics"
        college = "University of Toronto"
        dates = "1998 - 2002"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Professional"

        [[params.language.list]]
        language = "Russian"
        level = "Native"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Cooking"

        [[params.interests.list]]
        interest = "Skiing"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "**Senior full Stack Developer**<br/>Extensive experience with Continuous Integration, Continuous Delivery and Continuous Deployment pipelines<br/>Strong Web development skills attained by working with various web frameworks<br/>Proficient in all aspects of software development lifecycle<br/>Hands-on 24/7 production support experience<br/>Great communication and interpersonal skills acquired by presenting projects and mentoring junior developers"
    
    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Senior Full Stack Developer"
        dates = "2014 - Present"
        company = "Stars Technologies, Toronto"
        details = "Created internal configuration application (Angular 5, PrimeNG, Spring MVC 5, DB2, MyBatis<br/>Designed and implemented various reports (Angular 5, PrimeNG, Spring MVC 5, DB2, MyBatis, JSP)<br/>Designed and implemented customer support form application to help with customer communication, document submission (Angular 1, Grails/Groovy, Gulp)<br/>Wrote multiple tools and reports (Ext JS 6, Grails 3/Groovy, DB2, MyBatis)<br/>Created Restful API for online rewards store (Grails 3/Groovy)<br/>Designed and implemented Restful API for leaderboards (Grails 3/Groovy)" 

        [[params.jobs.list]]
        position = "Java Web Developer "
        dates = "2006 - 2014"
        company = "Afilias Canada, Toronto"
        details = "Designed and implemented a web client application for domain, host and contact management (Wicket framework, Spring, Java, JDBC, HTML)<br/>Developed Searchable Whois web application (Spring MVC, Java, HTML, CSS, JavaScript, Elasticsearch)<br/>Designed and developed pricing analysis tool for financial department (Java, SQL, JUnit) <br/>Enhanced various existing testing frameworks (Scala, Robot Framework)<br/>Redesigned existing web and server side applications to implement the requirements of new clients (Struts, Java, XML, SQL) <br/>Practiced Test Driven Development with extensive JUnit test cases<br/>Provided leadership to group of developers on deploying new registries<br/>Managed small projects that required collaboration between various departments"

        [[params.jobs.list]]
        position = "Application Developer"
        dates = "2002 - 2006"
        company = "PBS Systems, Toronto"
        details = "Developed client-server application for parts management and order processing (Java, AWT, SWING, JDBC, NetBeans 5.0, MySQL)<br/>Created reports for parts managers and physical inventory (Java, PDF, JDBC)<br/>Developed bridge application for data transferring from internal system to an external company (Java, JDBC)<br/>Maintenance and production support of client/server applications for parts, service, accounting and showroom (C/C++, Visual C++, Linux, Perl, Unix Shell script, ODBC)<br/>Managed client databases, performed database upgrades, performance tuning, backed up data, looked after data consistency (Informix, Linux/Unix, SQL)"

        [[params.jobs.list]]
        position = "Programmer"
        dates = "May - Sep 2000"
        company = "Autros Health Care Solutions, Toronto"
        details = "Developed Serial Client Bridge emulator to transfer data from/to TCP/IP to/from Serial Port (Power Builder)<br/>Wrote program for distributed access finger print login UareU (C++)"

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Angular 5 and Angular 1"
        level = "70%"
                
        [[params.skills.list]]
        skill = "Javascript"
        level = "98%"

        [[params.skills.list]]
        skill = "ExtJs"
        level = "95%"

        [[params.skills.list]]
        skill = "Grails and Groovy"
        level = "95%"

        [[params.skills.list]]
        skill = "Java"
        level = "95%"

        [[params.skills.list]]
        skill = "Spring MVC"
        level = "70%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
